name: Deploy to Firebase

on:
  push:
    branches:
      - master  # ou a branch que você deseja usar para o deploy

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npx jest --coverage  # ou o comando específico para rodar os testes do seu projeto

      - name: save artfacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/Icov-report/*
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: npm run build  # ou o comando específico para construir seu projeto

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
